Travix/Travix/Models/AccountUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Travix.Models
{
    public class AccountUser
    {
        [Required(ErrorMessage="Please enter Login")]
        [StringLength(50)]
        public string Login { get; set; }

        [Required(ErrorMessage = "Please enter Password")]
        [RegularExpression(@"^(?=.*[a-z]).{3,8}$")] // should be some strong regex
        public string Password { get; set; }
    }
}

Travix/Travix/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Travix.Controllers
{
    public class ErrorController : Controller
    {
        //
        // GET: /Error/

        public ActionResult NotFound()
        {
            return View();
        }

        public ActionResult DefaultError()
        {
            return View();
        }
    }
}

Travix/Travix/Controllers/GlobalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Travix.Helpers;

namespace Travix.Controllers
{
    public class GlobalController : Controller
    {
        //
        // GET: /Global/

        [HttpPost]
        public ActionResult SetCulture(string culture)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);
            // Save culture in a cookie
            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;   // update cookie value
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }

            Response.Cookies.Add(cookie);
            return RedirectToAction("Index", "Home");
        }
    }
}

Travix/Travix/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace Travix.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {

            return View();
        }

    }
}

Travix/Travix/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Services.Description;
using DAL.Abstractions;
using AutoMapper;
using BE.DomainModels;
using BLL.Abstractions;
using BLL.Services;
using DAL.UnitOfWork;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Ninject;
using Travix.Models;

namespace Travix.Controllers
{
    public class UserController : Controller
    {

        //
        // GET: /User/

        private readonly IUserService _iUserService;
        
        public UserController(IUserService iUserService)
        {
            _iUserService = iUserService;
        }

        [Authorize]
        public JsonResult Index()
        {
            var currentUser = _iUserService.GetUserByLogin(User.Identity.Name);

            if (currentUser == null)
                return null;

            return Json(currentUser, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult SignIn(AccountUser user, string returnUrl)
        {
            if (User.Identity.IsAuthenticated)
                RedirectToAction("Index", "Home");
            
            if (!ModelState.IsValid)
                // If we got this far, something failed, redisplay form
                return View("SignIn");

            var domainUser = Mapper.Map<AccountUser, User>(user);
            domainUser.Login = Server.HtmlDecode(domainUser.Login);

            bool isExist;

            using (var unitOfWork = (IUnitOfWork)DependencyResolver.Current.GetService(typeof(IUnitOfWork)))
            {
                isExist = _iUserService.Login(domainUser.Login, domainUser.Password);
            }

            if (!isExist)
            {
                ModelState.AddModelError("CustomMessage", "The user name or password provided is incorrect.");
                return View("SignIn");
            }

            FormsAuthentication.SetAuthCookie(domainUser.Login, false);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult SingOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

    }
}

Travix/Travix/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>It's home page</h2>

Travix/Travix/Views/Shared/_Layout.cshtml
@{
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
}
@helper selected(string c, string culture)
{
    if (c == culture)
    {
    @:checked="checked"
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="menu">
        @if (Request.IsAuthenticated)
        {
            <li>
                <a href="/User/Index">
                    User Info
                </a>
            </li>
             <li>
                <a href="/User/SingOut">
                    @Resources.Resource.SingOut
                </a>
            </li>

        }
        else
        {
            <li>
                <a href="/User/SignIn">
                    @Resources.Resource.LogIn
                </a>
            </li>
        }
    </nav>

    <div class="container">
        @RenderBody()
    </div>
    <footer class="footer">

        @using (Html.BeginForm("SetCulture", "Global", FormMethod.Post))
        {
            <fieldset>
                <legend>@Resources.Resource.Lang</legend>
                <div class="control-group">
                    <div class="controls">
                        <label for="ru">
                            <input name="culture" id="ru" value="ru" type="radio" @selected("ru", culture)/>
                            Russian
                        </label>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <label for="en">
                            <input name="culture" id="en" value="en" type="radio" @selected("en", culture)/>
                            English
                        </label>
                    </div>
                </div>

            </fieldset>
        }
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

    <!--should be in js file-->
    <script type="text/javascript">
        (function ($) {
            $("input[type = 'radio']").click(function () {
                $(this).parents("form").submit(); // post form
            });

        })(jQuery);

    </script>
    <style>
        footer.footer {
            position: absolute;
            bottom: 0;
            width: 100%;
        }

        div.container {
            width: 800px;
            margin: 0 auto;
            text-align: center;
        }

        nav.menu {
        }
    </style>
</body>
</html>

Travix/Travix/Views/User/SignIn.cshtml
@{
    ViewBag.Title = "SignIn";
    @model Travix.Models.AccountUser
}

<h2>SignIn</h2>

<form method="post" action="@Url.Action("SignIn")">

    <div>
         @Html.ValidationSummary(false)
         @Html.AntiForgeryToken()
        <div>
           <input  placeholder="Username" type="text"
                   name="Login"/>
        </div>
        <div>
            <input type="password" placeholder="Password"
                   name="Password"/>
        </div>

        @Html.ValidationMessage("CustomError")

        <input type="submit" value="Sign in"/>
    </div>
</form>